[[Kissat]]
arch = "aarch64"
git-tree-sha1 = "c2951abc9924b36f04644828d7d25d3b51b2bb8f"
os = "macos"

    [[Kissat.download]]
    sha256 = "65f38e9393f21de6caea11bdcd1ef6a1d82cb8a9b647b0c5b2cfd9d7d91dffaa"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v3.0.0+0/Kissat.v3.0.0.aarch64-apple-darwin.tar.gz"
[[Kissat]]
arch = "aarch64"
git-tree-sha1 = "6de6ddfdfdd6a6a089cd48738f0c9f510178e6e7"
libc = "glibc"
os = "linux"

    [[Kissat.download]]
    sha256 = "806a484c05c09692983bec6722ed2954b6555c9023f8232c6cf13d2758dc8377"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v3.0.0+0/Kissat.v3.0.0.aarch64-linux-gnu.tar.gz"
[[Kissat]]
arch = "aarch64"
git-tree-sha1 = "4326381e281fef7096ef0ef4379163134acaec10"
libc = "musl"
os = "linux"

    [[Kissat.download]]
    sha256 = "6a99e9c5615ed575d64d227e52dc2d97063a3a88cc5caf7d568e56fcdc7c88e5"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v3.0.0+0/Kissat.v3.0.0.aarch64-linux-musl.tar.gz"
[[Kissat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ce59eec166742efbeda8b0ea4e698249dfba0e6a"
libc = "glibc"
os = "linux"

    [[Kissat.download]]
    sha256 = "fc60bd0bd676ba70125c6cceac8fcb8e716abcad714d74e4b29b43b16440e1ad"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v3.0.0+0/Kissat.v3.0.0.armv6l-linux-gnueabihf.tar.gz"
[[Kissat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1d1e594e17debaa3e9017b83bf6e917ca8bc5002"
libc = "musl"
os = "linux"

    [[Kissat.download]]
    sha256 = "fc84c70582a9ab2f07a20a45cd22767f54468507bb29de1fbc152a2512a64c92"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v3.0.0+0/Kissat.v3.0.0.armv6l-linux-musleabihf.tar.gz"
[[Kissat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8e019fb88684f3f856fa0e3c87564935a2e64045"
libc = "glibc"
os = "linux"

    [[Kissat.download]]
    sha256 = "8cc0a5553b6cbb35921704681fd2174a4a7d79658242bb32328222fbc2df13a2"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v3.0.0+0/Kissat.v3.0.0.armv7l-linux-gnueabihf.tar.gz"
[[Kissat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "409c395146e297577ae1c0c129e1865c72b180da"
libc = "musl"
os = "linux"

    [[Kissat.download]]
    sha256 = "895c30e98617827ab6feadac08861f16d803eb934d48b34bd4df3c0b372ff053"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v3.0.0+0/Kissat.v3.0.0.armv7l-linux-musleabihf.tar.gz"
[[Kissat]]
arch = "i686"
git-tree-sha1 = "987d6086b2590fe1a1c91e6ed7d07c8b10220890"
libc = "glibc"
os = "linux"

    [[Kissat.download]]
    sha256 = "97dc49b82ccadb72a8906fd67519d1e0a0637d73261bafe37bf6a74d4e3dfb53"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v3.0.0+0/Kissat.v3.0.0.i686-linux-gnu.tar.gz"
[[Kissat]]
arch = "i686"
git-tree-sha1 = "8167e00903f9932c1bc24e761f64aabebcc6d218"
libc = "musl"
os = "linux"

    [[Kissat.download]]
    sha256 = "93dd15c9e8660b3d5886c65640bec0e109f322f8b3467aca749e7f6545718177"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v3.0.0+0/Kissat.v3.0.0.i686-linux-musl.tar.gz"
[[Kissat]]
arch = "powerpc64le"
git-tree-sha1 = "e7427357d43b9b409cc7be28e87ad8645d0a7aad"
libc = "glibc"
os = "linux"

    [[Kissat.download]]
    sha256 = "fbc2696b721c390040e30948b13a2ddacdf7c242e917c9a9009978b4144a1aa9"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v3.0.0+0/Kissat.v3.0.0.powerpc64le-linux-gnu.tar.gz"
[[Kissat]]
arch = "x86_64"
git-tree-sha1 = "2c7d217cb4bbe530bb40cc009d169d0f4e047a29"
os = "macos"

    [[Kissat.download]]
    sha256 = "d8bea58b24f6cbaa67b1b73b1c16d3fea3cb168a0cb2ab3b4f1d72e919d6e62f"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v3.0.0+0/Kissat.v3.0.0.x86_64-apple-darwin.tar.gz"
[[Kissat]]
arch = "x86_64"
git-tree-sha1 = "97c8d6272ffe420241a5ec8f5bf6702987307e29"
libc = "glibc"
os = "linux"

    [[Kissat.download]]
    sha256 = "65767ef04c47cdea855a1be623a2687a7c129083a658f9a5ab97446cac1afe1d"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v3.0.0+0/Kissat.v3.0.0.x86_64-linux-gnu.tar.gz"
[[Kissat]]
arch = "x86_64"
git-tree-sha1 = "d447ff79234189681f6abaa81dc2e604d5ccc423"
libc = "musl"
os = "linux"

    [[Kissat.download]]
    sha256 = "10a08052bcb83a974ea6e64e5b4ae8c1227d39dec780af9248ce56dd79a741d9"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v3.0.0+0/Kissat.v3.0.0.x86_64-linux-musl.tar.gz"
[[Kissat]]
arch = "x86_64"
git-tree-sha1 = "00d2f0607a593b3f7a22a7625b8ef32a31104f46"
os = "freebsd"

    [[Kissat.download]]
    sha256 = "09a9ad6ced847ca74873803911fc6fe3f2252277ab31132218c8f5ed9f750344"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v3.0.0+0/Kissat.v3.0.0.x86_64-unknown-freebsd.tar.gz"
