[[Kissat]]
arch = "aarch64"
git-tree-sha1 = "c3858321ebbb5b1f4b475505deb730be77559881"
os = "macos"

    [[Kissat.download]]
    sha256 = "3eac2db1fc9ec8b53ff8162fee03c0bb7031d50869efad238598394dc552b616"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v2.0.0+0/Kissat.v2.0.0.aarch64-apple-darwin.tar.gz"
[[Kissat]]
arch = "aarch64"
git-tree-sha1 = "80f4d52e6e9b9b8d33e348a5e458fc431980b9e9"
libc = "glibc"
os = "linux"

    [[Kissat.download]]
    sha256 = "1dd09993e2cde75b1580d52fada5e593b629489bffe8db962adf72b387fb76fe"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v2.0.0+0/Kissat.v2.0.0.aarch64-linux-gnu.tar.gz"
[[Kissat]]
arch = "aarch64"
git-tree-sha1 = "271e64e50d6550cb9d9695ccee18d815675aae2a"
libc = "musl"
os = "linux"

    [[Kissat.download]]
    sha256 = "c85ae36bcc13380d15a1657f4a310da11a137db5b986210122296489e74dfa8a"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v2.0.0+0/Kissat.v2.0.0.aarch64-linux-musl.tar.gz"
[[Kissat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2b3446791ebe8587f0b7f7fef103296551c8137a"
libc = "glibc"
os = "linux"

    [[Kissat.download]]
    sha256 = "62f5ba644e67069c77549c11267ab5ccab0eef8ef45f964230901734311988de"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v2.0.0+0/Kissat.v2.0.0.armv6l-linux-gnueabihf.tar.gz"
[[Kissat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "100f209a23afabf605f68ac42b1efc23556e749e"
libc = "musl"
os = "linux"

    [[Kissat.download]]
    sha256 = "1d4142637a24e9e540d2acdbc29ae6f384e65648d503356ca4d7bf50adfb9387"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v2.0.0+0/Kissat.v2.0.0.armv6l-linux-musleabihf.tar.gz"
[[Kissat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "39dd14ea8e4ac2635b84299df49718f571ee3351"
libc = "glibc"
os = "linux"

    [[Kissat.download]]
    sha256 = "69f8650928bdf99a1044c03f13892a45c3a1d48fe7ed65191f5a6746136c0eb3"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v2.0.0+0/Kissat.v2.0.0.armv7l-linux-gnueabihf.tar.gz"
[[Kissat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0725a329bf48cf7c96fb7f5d882002a2e37535c3"
libc = "musl"
os = "linux"

    [[Kissat.download]]
    sha256 = "1138d3d3c0bc4d62910e07ff73f1668292bd9af24063cfb896e77f9bb87f8e48"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v2.0.0+0/Kissat.v2.0.0.armv7l-linux-musleabihf.tar.gz"
[[Kissat]]
arch = "i686"
git-tree-sha1 = "baf70cdb6b78c6f131524b3953a8c91d2db3734c"
libc = "glibc"
os = "linux"

    [[Kissat.download]]
    sha256 = "5db56c350ca19bf00cdf2358ac2f178b7e4d4fbf4a8aff5893191fff76b7f706"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v2.0.0+0/Kissat.v2.0.0.i686-linux-gnu.tar.gz"
[[Kissat]]
arch = "i686"
git-tree-sha1 = "d6c9cd7601658336a9fadb2ef2b1f5c3fa10e6e1"
libc = "musl"
os = "linux"

    [[Kissat.download]]
    sha256 = "8b233f23abcf921a87414f977a38610980ca1cd3b291c3c1aa257cf51af9e92d"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v2.0.0+0/Kissat.v2.0.0.i686-linux-musl.tar.gz"
[[Kissat]]
arch = "powerpc64le"
git-tree-sha1 = "2160e2454af07dce38316801156697b502088d1e"
libc = "glibc"
os = "linux"

    [[Kissat.download]]
    sha256 = "c91870c8a1acbc3b9a0de8a766f0a650a338a7bc5b427e209690856ee61532ae"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v2.0.0+0/Kissat.v2.0.0.powerpc64le-linux-gnu.tar.gz"
[[Kissat]]
arch = "x86_64"
git-tree-sha1 = "a03b802c7530758497004c2eeb31d9f3cb7aede4"
os = "macos"

    [[Kissat.download]]
    sha256 = "3cfd6f8eb9d9c426c7566b2528366698297d457dae3d8267ed0d54d30cc2e190"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v2.0.0+0/Kissat.v2.0.0.x86_64-apple-darwin.tar.gz"
[[Kissat]]
arch = "x86_64"
git-tree-sha1 = "fb105bd8d5b0e27e1828b0de3b2758da71ef87ab"
libc = "glibc"
os = "linux"

    [[Kissat.download]]
    sha256 = "c02a8fdaea03776bee66ce33dd8a39cc117ab14d0281072dc8013ea399e94d58"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v2.0.0+0/Kissat.v2.0.0.x86_64-linux-gnu.tar.gz"
[[Kissat]]
arch = "x86_64"
git-tree-sha1 = "8eb47c9a5751c9ec952f21923a4a812bae6b9f80"
libc = "musl"
os = "linux"

    [[Kissat.download]]
    sha256 = "cae7ff209e83afd84e561541738f0bb094ed21acca9825fb85e46ad7a364c5ca"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v2.0.0+0/Kissat.v2.0.0.x86_64-linux-musl.tar.gz"
[[Kissat]]
arch = "x86_64"
git-tree-sha1 = "07ddf27825d11698e1b78c82388f67360661d177"
os = "freebsd"

    [[Kissat.download]]
    sha256 = "9bd56110c50843cb2255ba4d136494b15b86d1fb2a18fe04320e60ad86a876dc"
    url = "https://github.com/JuliaBinaryWrappers/Kissat_jll.jl/releases/download/Kissat-v2.0.0+0/Kissat.v2.0.0.x86_64-unknown-freebsd.tar.gz"
