# Autogenerated wrapper script for Kissat_jll for aarch64-apple-darwin
export kissat, libkissat

JLLWrappers.@generate_wrapper_header("Kissat")
JLLWrappers.@declare_library_product(libkissat, "@rpath/libkissat.so")
JLLWrappers.@declare_executable_product(kissat)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libkissat,
        "lib/libkissat.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        kissat,
        "bin/kissat",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
